/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing3;

/**
 * Michael Jonathan Setiawan
 * 58170468
 */

import javax.swing.JOptionPane;
public class KasirSederhana extends javax.swing.JFrame {

    /**
     * Creates new form KasirSederhana
     */
    public KasirSederhana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nasgorRD = new javax.swing.JRadioButton();
        migorRD = new javax.swing.JRadioButton();
        soayRD = new javax.swing.JRadioButton();
        sokamRD = new javax.swing.JRadioButton();
        naRD = new javax.swing.JRadioButton();
        harganasgorField = new javax.swing.JTextField();
        hargamigorField = new javax.swing.JTextField();
        hargasoayField = new javax.swing.JTextField();
        hargasokamField = new javax.swing.JTextField();
        harganaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jumlahnasgorField = new javax.swing.JTextField();
        jumlahmigorField = new javax.swing.JTextField();
        jumlahsoayField = new javax.swing.JTextField();
        jumlahsokamField = new javax.swing.JTextField();
        jumlahnaField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jumlahhargaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WARUNG MANTAP SEDAP");

        nasgorRD.setText("Nasi Goreng");
        nasgorRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasgorRDActionPerformed(evt);
            }
        });

        migorRD.setText("Mie Goreng");
        migorRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                migorRDActionPerformed(evt);
            }
        });

        soayRD.setText("Soto Ayam");
        soayRD.setToolTipText("");
        soayRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soayRDActionPerformed(evt);
            }
        });

        sokamRD.setText("Sop Kambing");
        sokamRD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sokamRDActionPerformed(evt);
            }
        });

        naRD.setText("Nasi");

        harganaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harganaFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Jumlah");

        jumlahmigorField.setToolTipText("");

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Jumlah harga");

        jLabel4.setText("x");

        jLabel5.setText("x");

        jLabel6.setText("x");

        jLabel7.setText("x");

        jLabel8.setText("x");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jumlahhargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(44, 44, 44)
                                .addComponent(jButton3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(migorRD)
                                            .addComponent(nasgorRD)
                                            .addComponent(soayRD)
                                            .addComponent(sokamRD)
                                            .addComponent(naRD))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(harganasgorField, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(hargamigorField)
                                            .addComponent(hargasoayField)
                                            .addComponent(hargasokamField)
                                            .addComponent(harganaField))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahmigorField)
                                    .addComponent(jumlahsoayField)
                                    .addComponent(jumlahsokamField)
                                    .addComponent(jumlahnaField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addGap(17, 17, 17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jumlahnasgorField)))))
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nasgorRD)
                    .addComponent(harganasgorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahnasgorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(migorRD)
                    .addComponent(hargamigorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahmigorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soayRD)
                    .addComponent(hargasoayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahsoayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sokamRD)
                    .addComponent(hargasokamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahsokamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naRD)
                    .addComponent(harganaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahnaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jumlahhargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nasgorRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasgorRDActionPerformed
        int nasigoreng = 15000;

        if (nasgorRD.isSelected()) {
            harganasgorField.setText("" + nasgorRD.getText());
            harganasgorField.setText("" + nasigoreng);
        } else {
            harganasgorField.setText("");
        }
    }//GEN-LAST:event_nasgorRDActionPerformed

    private void migorRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_migorRDActionPerformed
        int miegoreng = 15000;

        if (migorRD.isSelected()) {
            hargamigorField.setText("" + migorRD.getText());
            hargamigorField.setText("" + miegoreng);
        } else {
            hargamigorField.setText("");
        }
    }//GEN-LAST:event_migorRDActionPerformed

    private void soayRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soayRDActionPerformed
        int sotoayam = 15000;

        if (soayRD.isSelected()) {
            hargasoayField.setText("" + soayRD.getText());
            hargasoayField.setText("" + sotoayam);
        } else {
            hargasoayField.setText("");
        }
    }//GEN-LAST:event_soayRDActionPerformed

    private void sokamRDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sokamRDActionPerformed
        int sotokambing = 25000;

        if (sokamRD.isSelected()) {
            hargasokamField.setText("" + sokamRD.getText());
            hargasokamField.setText("" + sotokambing);
        } else {
            hargasokamField.setText("");
        }
    }//GEN-LAST:event_sokamRDActionPerformed

    private void harganaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harganaFieldActionPerformed
        int nasi = 5000;

        if (naRD.isSelected()) {
            harganaField.setText("" + naRD.getText());
            harganaField.setText("" + nasi);
        } else {
            harganaField.setText("");
        }
    }//GEN-LAST:event_harganaFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total = 0;

        if (nasgorRD.isSelected()) {
            String NG = jumlahnasgorField.getText();
            int jumlahnasgor = Integer.parseInt(NG);
            int harganasgor = jumlahnasgor * 15000;
            total = total + harganasgor;
        }
        if (migorRD.isSelected()) {
            String MG = jumlahmigorField.getText();
            int jumlahmigor = Integer.parseInt(MG);
            int hargamigor = jumlahmigor * 15000;
            total = total + hargamigor;
        }
        if (soayRD.isSelected()) {
            String SA = jumlahsoayField.getText();
            int jumlahsoay = Integer.parseInt(SA);
            int hargasoay = jumlahsoay * 15000;
            total = total + hargasoay;
        }
        if (sokamRD.isSelected()) {
            String SK = jumlahsokamField.getText();
            int jumlahsokam = Integer.parseInt(SK);
            int hargasokam = jumlahsokam * 25000;
            total = total + hargasokam;
        }
        if (naRD.isSelected()) {
            String NA = jumlahnaField.getText();
            int jumlahna = Integer.parseInt(NA);
            int hargana = jumlahna * 5000;
            total = total + hargana;
        }

        jumlahhargaField.setText("" + total);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jumlahnasgorField.setEditable(false);
        jumlahnasgorField.setText("");
        jumlahmigorField.setEditable(false);
        jumlahmigorField.setText("");
        jumlahsoayField.setEditable(false);
        jumlahsoayField.setText("");
        jumlahsokamField.setEditable(false);
        jumlahsokamField.setText("");
        jumlahnaField.setEditable(false);
        jumlahnaField.setText("");

        jumlahhargaField.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Keluar program", "Exit",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (x == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasirSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasirSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasirSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasirSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasirSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargamigorField;
    private javax.swing.JTextField harganaField;
    private javax.swing.JTextField harganasgorField;
    private javax.swing.JTextField hargasoayField;
    private javax.swing.JTextField hargasokamField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jumlahhargaField;
    private javax.swing.JTextField jumlahmigorField;
    private javax.swing.JTextField jumlahnaField;
    private javax.swing.JTextField jumlahnasgorField;
    private javax.swing.JTextField jumlahsoayField;
    private javax.swing.JTextField jumlahsokamField;
    private javax.swing.JRadioButton migorRD;
    private javax.swing.JRadioButton naRD;
    private javax.swing.JRadioButton nasgorRD;
    private javax.swing.JRadioButton soayRD;
    private javax.swing.JRadioButton sokamRD;
    // End of variables declaration//GEN-END:variables
}
